### ISSUE TITLE
[BUG] Previously-reported issue with the `element` field on `origins:choice` not actually fixed.

### ISSUE THREAD

**Issue by JadeJuno** [SnaveSutit/origins-mod-vscode-extension#12]
**Describe the bug**
On issue #9 I mentioned that the `element` field checks for an array instead of an object, and the issue is closed. It, however, is not fixed.

**To Reproduce**
1. Make Action-related power
2. Add `origins:choice` action
3. Add `actions` field and make it an array
4. On any of the objects in the `actions` array, add an `element` field and make it an object
5. See error,

**Expected behavior**
It should let me use an object for the `element` field.

**Screenshots**
![image](https://user-images.githubusercontent.com/53577918/160968794-a50bf4c7-2789-40cd-83e9-152acb753990.png)

**Comment by SnaveSutit** [comment]
Ah, whoops. Must've skimmed over that detail
