### ISSUE TITLE
[BUG] power:stacking_status_effect duration_per_tick should be duration_per_stack in required properties

### ISSUE THREAD

**Issue by H077y** [SnaveSutit/origins-mod-vscode-extension#13]
**Describe the bug**
After using `origins:multiple` with one of the powers titled `effects`, the plugin detects this as an effect list and states that I'm missing `duration_per_tick`.
I expect that this also occurs with other things things inside `origins:multiple`, but I haven't tested.

**To Reproduce**
```
"type":"origins:multiple",
"effects": {
    code
}
```

**Expected behavior**
There should be no error as it is not an effects list, it is an `origins:multiple` power.

**Screenshots**
![image](https://user-images.githubusercontent.com/64114013/161241159-00f55d4e-07df-4266-b6e0-d7a0f5cb4cdd.png)

**Comment by H077y** [comment]
After checking some more, it appears that this happens with every stacking status effect, however, I do not see `duration_per_tick` in the origins docs, so why does the plugin enforce it?
![image](https://user-images.githubusercontent.com/64114013/161243181-4a799410-c387-4358-af4b-c58bc0e93ce6.png)

**Comment by SnaveSutit** [comment]
Probably because I made a typo
