### ISSUE TITLE
[FR] Change color of errors to red instead of yellow

### ISSUE THREAD

**Issue by JadeJuno** [SnaveSutit/origins-mod-vscode-extension#18]
**Is your feature request related to a problem? Please describe.**
Since I started using this extension, I felt that the formatting errors -such as a required field not being inserted or having an incorrect data type somewhere- should be counted as errors and not just warnings. That way, it'd allow for the possibility of actual warnings messages.

**Describe the solution you'd like**
I want to have errors be actual errors instead of warning.

**Describe alternatives you've considered**
Changing the color of errors to red

*PD: it is 4 AM at time of writing this and I have no idea if any of this is coherent, so excuse me if it isn't...*

**Comment by SnaveSutit** [comment]
Not sure if this is possible. I'll look into it though

**Comment by JadeJuno** [comment]
Yeah I still don't fully get how VSC extensions work, but I've seen things like Datapack Helper Plus use Errors so I'd guess it's possible

**Comment by SnaveSutit** [comment]
They are using a custom language server. Not JSON Schemas. I have no custom code to provide VSCode with errors, everything you see is using vanilla VSCode behavior.
I'm not gonna implement a language server for JSON files just to change the color of the Schema errors
