### ISSUE TITLE
[BUG] JSON Text Components

### ISSUE THREAD

**Issue by sylenthuntress** [SnaveSutit/origins-mod-vscode-extension#20]
**Describe the bug**
JSON Text Components in powers like `origins:tooltip` are being errored, as it requires an object

**To Reproduce**
1. Make a tooltip power
2. Use JSON Text Components
3. Text Components are errored, saying it needs to be a string

**Expected behavior**
As the wiki says, JSON Text Components should not be errored, as they work in-game.

**Screenshots**
![image](https://user-images.githubusercontent.com/91935048/163892832-252944e6-8d90-4fe6-bf87-d2f770afbc16.png)

**Comment by SnaveSutit** [comment]
If you find any more places where this issue comes up, comment them here. I've fixed the one you've mentioned.
