### ISSUE TITLE
[FR] New Content

### ISSUE THREAD

**Issue by sylenthuntress** [SnaveSutit/origins-mod-vscode-extension#24]
**Is your feature request related to a problem? Please describe.**
Any content from 1.6.0 is missing.

**Describe the solution you'd like**
All content from 1.6.0 should be added to the extension now that it has been documented.

**Describe alternatives you've considered**
N/A

**Comment by SnaveSutit** [comment]
Is there a list of just all the new content added?

**Comment by sylenthuntress** [comment]
https://github.com/apace100/apoli/releases/tag/v2.5.0 Has a list of all new action types, power types, and condition types.

There are a few specific fields that aren't in the changelog, I can send an issue or comment here if I come across them. 

I believe there's also the new operations, and the new resource field in attribute modifiers, which are both documented.

**Comment by SnaveSutit** [comment]
Yeah, just send in anything that you notice is missing and I'll add it.
Meanwhile I'll add the ones documented in the changelog.
