### ISSUE TITLE
Add support for Apugli

### ISSUE THREAD

**Issue by SnaveSutit** [SnaveSutit/origins-mod-vscode-extension#31]
https://apugli.readthedocs.io/en/latest/types/entity_condition_types/

**Comment by ChrysanthCow** [comment]
I'd ultimately wait until the documentation is complete, which I'll try to get to soon.

**Comment by ChrysanthCow** [comment]
Documentation has been updated to match latest version and I don't plan on updating outside of patches for a while, so you can now go ahead.
