### ISSUE TITLE
[BUG] Modify Velocity uses "axis" instead of "axes"

### ISSUE THREAD

**Issue by LuaDotExe** [SnaveSutit/origins-mod-vscode-extension#34]
**Describe the bug**
The Modify Velocity Power Type says to use "axis", but the key is "axes".

**To Reproduce**
1. Create a Power
2. Set "type" to "origins:modify_velocity"
3. Fill out applicable information
4. Specify an "axis"
5. The "axis" specification does not work in-game
6. Correct to "axes"
7. The "axes" specification works in-game

**Expected behavior**
Suggest "axes" instead of "axis"

**Screenshots**
![image](https://user-images.githubusercontent.com/77378441/212360663-e7d67814-60ab-4c54-a78d-4e499bc77283.png)
![image](https://user-images.githubusercontent.com/77378441/212360689-20649ff5-ff4a-4eba-86d5-65a99e54810e.png)

**Comment by SnaveSutit** [comment]
This is actually a change made by a recent update that I happened to miss. Fixed in next push
