### ISSUE TITLE
[BUG] Irritating Typo

### ISSUE THREAD

**Issue by sylenthuntress** [SnaveSutit/origins-mod-vscode-extension#35]
**Describe the bug**
Typo in the origins:modify_velocity error checking

**To Reproduce**
1. Create a power
2. Give the newly-created power the origins:modify_velocity power type
3. Add the `axes` field
4. Recieve an error that you need to have the `axis` field
5. 
**Expected behavior**
`axes` is the correct spelling used by the mod as a plural of `axis`, so there should be no error when that field is used.

**Screenshots**
![image](https://user-images.githubusercontent.com/91935048/212573853-64c31336-0828-45a7-94ca-81ead288ef42.png)

**Comment by JadeJuno** [comment]
Wasn't this already fixed? #34

**Comment by SnaveSutit** [comment]
It should be fixed in 2.1.7

**Comment by JadeJuno** [comment]
Can confirm, no errors on my side (added a typeless condition to show that the extension is working.)
![image](https://user-images.githubusercontent.com/53577918/214437707-c64096b8-f86e-4433-be73-8460b5534a1f.png)
Please close whenever possible.
