### ISSUE TITLE
[BUG] ID Regex ignores the fact that "minecraft"-namespaced IDs can skip the namespace

### ISSUE THREAD

**Issue by JadeJuno** [SnaveSutit/origins-mod-vscode-extension#36]
**Describe the bug**
When using an ID in the `minecraft` ID (such as `minecraft:resistance` for the "Resistance" Status Effect, or `minecraft:stone` for the "Stone" block), you can skip the `minecraft` namespace, and it'll work the same (i.e. `resistance`, `stone`, etc.). This is not taken into account by the schema, and it will warn you if you use it like that.

**To Reproduce**
As an example of where to reproduce said error
1. Make a power with any Power Type (will use `origins:simple` for the example in the screenshots)
2. Add the following Entity Condition to the power:
```json
{
	"type": "origins:on_block",
	"block_condition": {
		"type": "origins:block",
		"block": "stone"
	}
}
```
3. See unwarranted warning on the line containing `"block": "stone"`

**Expected behavior**
The warning would not appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/53577918/214391895-f5d0814d-59e6-441e-b0c4-6618128af659.png)

***PD**: Hopefully this wasn't too hard to understand. I did my best to try to make this as comprehensible as possible.*

**Comment by SnaveSutit** [comment]
I've done this to enforce good habits.

**Comment by JadeJuno** [comment]
This screenshot comes from the Origins mod Source Code:
![image](https://user-images.githubusercontent.com/53577918/215136914-5d67427b-fe5a-49bf-a611-b4f71eb0d593.png)
Both are "good habits".
Please reconsider.

Edit: I just noticed that this screenshot is actually relevant to another issue, since the `class` field of `origins:attribute_modify_transfer` doesn't use this format of IDs.
Here's a better screenshot:
![image](https://user-images.githubusercontent.com/53577918/215137046-662ff3dd-3e44-41bd-94de-376f75b3498f.png)
