### ISSUE TITLE
[BUG] `apoli` namespace not detected for type IDs

### ISSUE THREAD

**Issue by JadeJuno** [SnaveSutit/origins-mod-vscode-extension#4]
**Describe the bug**
With Origins, you can use `apoli` instead of `origins` as the namespace of the IDs of powers and other stuff. This is useful for making datapacks and similars that don't require the Origins mod but the Apoli library (i.e. using the [CCPacks](https://www.curseforge.com/minecraft/mc-mods/custom-content-packs) mod.) This schema doesn't accept that though.

**To Reproduce**
1. Make a power file
2. Give it a Power Type that requires a specific field. For example, `origins:active_self`
3. Replace `origins:active_self` with `apoli:active_self`
4. See warning disappear.

**Expected behavior**
The warning should stay.

**Screenshots**
![image](https://user-images.githubusercontent.com/53577918/160845318-d19f6c33-58f1-457b-bc4c-23b520977c03.png)
![image](https://user-images.githubusercontent.com/53577918/160845405-c5507edb-8ff9-4a1e-b7bf-744d9e457d86.png)

**Comment by SnaveSutit** [comment]
This causes a lot of annoying code duplication, but I've fixed it.

**Comment by JadeJuno** [comment]
Is there no better way to make an alias system or smth?-
