### ISSUE TITLE
[BUG] `modifier` field incorrectly labelled as an error

### ISSUE THREAD

**Issue by sylenthuntress** [SnaveSutit/origins-mod-vscode-extension#41]
**Describe the bug**
When you use the `modifier` field as an array, it returns an error. The wiki confirms this, and there is a `modifiers` field in most (but not all) cases, so it's a fair mistake. However, it is possible to use the field as an array just like `modifiers`, which can be confirmed in in-game testing.

This bug is really annoying when I HAVE to use `modifier` as an array, like when modifying modifiers. 

**Expected behavior**
The field expects an "object" OR an "array", not just the latter, and therefore the extension should reflect that in its error parsing.

**Screenshots**
![image](https://github.com/SnaveSutit/origins-mod-json-schemas/assets/91935048/bcbc312c-f7d7-4c80-8bf7-08890270f043)
(Yes, this example works. Try it if you doubt it!)

**Comment by SnaveSutit** [comment]
I'll fix it this week.

**Comment by SnaveSutit** [comment]
Imagine saying you'll fix something and then sleeping for months

**Comment by SnaveSutit** [comment]
Fixed in next release
