### ISSUE TITLE
[BUG] Action On Callback Missing entity_action_gained

### ISSUE THREAD

**Issue by ghost** [SnaveSutit/origins-mod-vscode-extension#42]
**Describe the bug**
`entity_action_gained` seems to be missing from `action_on_callback`.

**To Reproduce**
1. Create datapack.
2. Create power.
3. Use `action_on_callback`.
4. Attempt to add `entity_action_gained`.

**Expected behavior**
I would expect it to work as defined in the [wiki](https://origins.readthedocs.io/en/latest/types/power_types/action_on_callback/#fields), with proper suggestions and corrections.

**Screenshots**
![image](https://github.com/SnaveSutit/origins-mod-json-schemas/assets/130942503/cbf95f86-e9e0-420b-8762-1766a8b96ca8)

**Comment by SnaveSutit** [comment]
Noted. I'll update it over the weekend.

**Comment by SnaveSutit** [comment]
Fixed in next release
