### ISSUE TITLE
[BUG] Tooltip Power Missing Field

### ISSUE THREAD

**Issue by ghost** [SnaveSutit/origins-mod-vscode-extension#44]
**Describe the bug**
So, the `Tooltip Power Type` is missing the `order` field.

**To Reproduce**
1. Create filepath `data/test/powers/test.json`
2. Make `test.json` an `apoli:tooltip` power.
3. Look at the field options provided.

**Expected behavior**
I would expect it to appear as an option, as specified in the [wiki](https://origins.readthedocs.io/en/latest/types/power_types/tooltip/#fields).
I should mention that at the time of writing this, the wiki is [bugged](https://discord.com/channels/734127708488859831/1125671814069243977/1125688332593139742) and the `priority` field should be `order`, but I expect that to change soon.

**Screenshots**
![image](https://github.com/SnaveSutit/origins-mod-json-schemas/assets/130942503/fa8c96f5-5b1e-499c-ba49-58a9e21f4665)

**Comment by SnaveSutit** [comment]
Fixed in next release
