### ISSUE TITLE
[FR] Fields In Multiple Power Type

### ISSUE THREAD

**Issue by ghost** [SnaveSutit/origins-mod-vscode-extension#45]
**Is your feature request related to a problem? Please describe.**
So, whenever you create a power, there are two main types, in my opinion, with the differentiator being if it is an `apoli:multiple` power or not. However, subpowers still retain fields that are irrelevant to the power as a whole. For example, name, description, badges, etc. Those types of fields should really only be part of the power as a whole. The only reason they could ever really be used is if you for some reason singled them out, which seems like such an edge case scenario that it will never happen. Another point of differentiation is the `condition` field, which does not work on `apoli:multiple` powers.

**Describe the solution you'd like**
First, remove `condition` as a field if the power is an `apoli:multiple` or its aliases.
Second, remove irrelevant fields from subpowers. I'll put a list below:
- `badges`
- `condition`
- `description`
- `hidden`
- `loading_priority`
- `name`
- `skill` (I'll put this here but I honestly have no idea what this does because I don't remember seeing it in the [Origins Wiki](https://origins.readthedocs.io/en/latest/search.html?q=skill) or any addon page I viewed. Maybe worth removing it entirely from the extension but I don't really know.)

**Describe alternatives you've considered**
I'm not really sure if there's any alternatives? Perhaps if there is a setting you could maybe make the old way an option, although it probably should not be the default. Otherwise, I just don't think the hassle it creates is worth the result.

**Comment by SnaveSutit** [comment]
I can remove condition from multiple, but the "extra fields" are part of the powers themselves, and removing them in the schema is harder than you'd think without creating tons of duplicate data

**Comment by ghost** [comment]
Is it possible remove the fields from the powers themselves and basically make them fields of the power file as a whole? Kind of like the first root object has those properties but the branches do not? So, they wouldn't be part of the power schema? I have no idea how any of this works, though so, you know, uneducated troll just throwing out ideas here.

**Comment by SnaveSutit** [comment]
Possibly, I'll look into it

**Comment by SnaveSutit** [comment]
Fixed in next release
