### ISSUE TITLE
[FR] Default Values

### ISSUE THREAD

**Issue by ghost** [SnaveSutit/origins-mod-vscode-extension#46]
**Is your feature request related to a problem? Please describe.**
This is very, very, incredibly minor thing, but when auto-completing the `inverted` field, it always defaults to `false`. If you're ever using it, then you're obviously making it `inverted:true`, so it makes little sense for it to default to `false`. Literally the smallest thing you can think of...but, you know, it's technically a point of improvement that probably takes almost no time, so might as well, right?

**Describe the solution you'd like**
Preferably, the auto-completion would fill in `"inverted": true` instead of `"inverted": false`. Also, it currently selects it, which is nice, but selecting it would be pretty redundant if it defaulted to `true`.

**Describe alternatives you've considered**
_Problem is not complex or important enough for alternatives._

**Comment by ghost** [comment]
A similar thing happens with `"hidden": false`.

**Comment by JadeJuno** [comment]
This is probably because its default value in Origins is `false`.

Not saying it as a reason to stay like that, just explaining why this is the case-

**Comment by SnaveSutit** [comment]
Fixed in next release
