### ISSUE TITLE
[BUG] Missing Global Powers

### ISSUE THREAD

**Issue by ghost** [SnaveSutit/origins-mod-vscode-extension#47]
**Describe the bug**
So, in one of the more recent updates, [global powers](https://origins.readthedocs.io/en/latest/json/global_power_set/) were added. They weren't present in the wiki until very recently, however. As such, the suggestions are, not unexpectedly, missing from the extension.

**To Reproduce**
1. Create file path `data/namespace/global_powers/test.json`
2. Attempt to create specify global powers in `test.json`.
3. Find suggestions missing.

**Expected behavior**
I would expect it to suggest the various [fields](https://origins.readthedocs.io/en/latest/json/global_power_set/#fields).

**Screenshots**
![image](https://github.com/SnaveSutit/origins-mod-json-schemas/assets/130942503/14f73e26-0a5f-42c6-94e0-6fd62bdc7c1e)

**Comment by SnaveSutit** [comment]
Fixed in next version
