### ISSUE TITLE
Unable to load schema of Origin Layer

### ISSUE THREAD

**Issue by Kawatt** [SnaveSutit/origins-mod-vscode-extension#49]
**Describe the bug**
The schema for origin layers doesn't load

**To Reproduce**
1. Make a `data/origins/origin_layers/origin.json` file
2. Add and opening and closing bracket
3. See error

**Expected behavior**
Schema loads and provides error checking and autocompletion.

**Screenshots**
![failed-schema](https://github.com/SnaveSutit/origins-mod-json-schemas/assets/99446786/581d133f-c049-4506-acdb-567056fd4b4a)

**Comment by SnaveSutit** [comment]
I think I forgot about the origin layers schema entirely.
I'll fix it tomorrow
