### ISSUE TITLE
[BUG] The Item Slot Data Type accepts "container.<slot_number>" literally

### ISSUE THREAD

**Issue by Kawatt** [SnaveSutit/origins-mod-vscode-extension#50]
**Describe the bug**
The Item Slot Data Type accepts "container.<slot_number>" and gives an error with (for example) "container.10"

**To Reproduce**
1. Make a power that accepts an Item Slot Data Type as an argument, like Drop Inventory
2. Type "container.10" in the slot array
3. See error

**Expected behavior**
"container." + number is accepted, "container.<slot_number>" is not

**Comment by Kawatt** [comment]
This is happens for any value with <slot_number>, not only container, i forgot to say

**Comment by SnaveSutit** [comment]
Whoops. Of course I did that.
I'll take a look at it tomorrow
