### ISSUE TITLE
[BUG] `origins:name` and `origins:type` Damage Condition Types seem to be swapped

### ISSUE THREAD

**Issue by JadeJuno** [SnaveSutit/origins-mod-vscode-extension#55]
**Describe the bug**
Pretty simple issue; The [`origins:name` Damage Condition Type](https://origins.readthedocs.io/en/latest/types/damage_condition_types/name/) is trying to use the Damage Type IDs, while the [`origins:type` Damage Condition Type](https://origins.readthedocs.io/en/latest/types/damage_condition_types/type/) is trying to use the old Damage Source Name system, when it should be the other way around.

**To Reproduce**

1. Make any power that needs a Damage Condition.
2. Make a Damage Condition with the type `origins:name`
3. Type a Damage Source Name in the `name` field (i.e. `onFire`)
4. See VSCode complain

For the opposite behavior:
1. Make any power that needs a Damage Condition.
2. Make a Damage Condition with the type `origins:type`
3. Try to type the ID of a Damage Type in the `damage_type` field (i.e. `minecraft:on_fire`)
4. The autocompletion will show Damage Source Names instead.

**Expected behavior**
`origins:type` should use Damage Type IDs, and `origins:name` should use Damage Source Names.

**Screenshots**
![image](https://github.com/user-attachments/assets/5c265289-5c5f-469c-8505-7543fd5b2f61)
![image](https://github.com/user-attachments/assets/57f8f303-151c-4639-afff-a17b231aad88)

**Comment by SnaveSutit** [comment]
[Fixed](https://github.com/SnaveSutit/origins-mod-json-schemas/commit/db026ab4748097e2146e51db87d8957f44a8f49d)
