### ISSUE TITLE
[BUG] Using JSON Text in an Origins JSON file says 'incorrect type, expected string' despite working in game

### ISSUE THREAD

**Issue by selenivee** [SnaveSutit/origins-mod-vscode-extension#57]
**Describe the bug**
The title explains it decently well, however using a JSON Text Component throws an "expected string." Sorry if this isn't done right.

**To Reproduce**
Use a JSON Text Component in an origins json (a good example being an example from the origins read the docs: https://origins.readthedocs.io/en/latest/types/data_types/text_component/ )

**Expected behavior**
No problem being marked

**My code and screenshots**
```json
{
    "name": {
        "text": "Nymph",
        "color": "#ffbded"
    },
    "description": {
        "text": "blah blah"
    },
    "icon": {
        "item": "minecraft:pink_stained_glass"
    },
    "impact": 0,
    "unchoosable": false,
    "loading_priority": 0
}
```

![image](https://github.com/user-attachments/assets/c17ab3fc-4ad1-4b8f-bbfe-8bf4c0f0cc8a)
![image](https://github.com/user-attachments/assets/0132710f-350d-4e89-9f04-2f7555b64cbb)

**Comment by SnaveSutit** [comment]
Oh cool, didn't know that was supported
