### ISSUE TITLE
[BUG] "Matches multiple schemas when only one must validate" on... opening a string?

### ISSUE THREAD

**Issue by Nidoskull** [SnaveSutit/origins-mod-vscode-extension#58]
**Describe the bug**
See screenshot; the extension seems to be picking up on something that's... perfectly fine, actually.

**To Reproduce**
I do not know what caused this error; I merely opened a file I had already created some time ago.

**Expected behavior**
No warnings for perfectly fine code.

**Screenshots**
![image](https://github.com/user-attachments/assets/20ff9c86-e9e2-4418-aa98-7f9bc54d6ae2)

**Comment by SnaveSutit** [comment]
Fixed https://github.com/SnaveSutit/origins-mod-json-schemas/commit/cda57978c185ea579740c86f1d06fba4ec94a196
